name: smartctl-exporter
base: core24
adopt-info: smartctl-exporter
summary: Export smartctl statistics to Prometheus
license: Apache-2.0
contact: solutions-engineering@lists.canonical.com
issues: https://github.com/canonical/smartctl-exporter-snap/issues
source-code: https://github.com/canonical/smartctl-exporter-snap
description: |
  This snap includes smartctl_exporter to provide smartctl statistics via Prometheus.
  Grafana dashboards can then be used to visualize the exported metrics, see for example:\
  https://grafana.com/grafana/dashboards/20204-smart-hdd/

  **How-To**
  ---

  **How to install the snap:**

     sudo snap install smartctl-exporter

  The snap will start collecting smartctl statistics via default port `9633` on localhost.

  **How to configure the service:**

  The smartctl-exporter can be configured by setting the snap configuration options.\
  For example:

     # Get all the configuration options
     sudo snap get smartctl-exporter

     # Set a different exporter bind-address
     sudo snap set smartctl-exporter web.listen-address=:9664

     # Restart the exporter service to apply the changes
     sudo snap restart smartctl-exporter

  **Reference**
  ---

  Available configurations options:

  - `web.listen-address`: the address smartctl-exporter binds to.
    The default is `:9633`.
  - `log.level`: the log level of the smartctl-exporter. One of: [debug, info, warn, error]
    The default is `info`.
  - `smartctl.device-exclude`: Regexp of device names to exclude from automatic scanning. (mutually exclusive to device-include)
  - `smartctl.device-include`: Regexp of device names to include in automatic scanning. (mutually exclusive to device-exclude)

  **Links**
  ---
  Upstream smartctl_exporter repository\
  https://github.com/prometheus-community/smartctl_exporter

grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  s390x:
  ppc64el:

apps:
  smartctl-exporter:
    daemon: simple
    command: bin/smartctl_exporter.wrapper
    restart-condition: on-failure
    plugs:
      - network-bind
      - block-devices

parts:
  smartctl-exporter:
    plugin: go
    source: https://github.com/prometheus-community/smartctl_exporter.git
    source-tag: v0.13.0
    source-type: git
    build-snaps:
      - go
    stage-packages:
      - smartmontools
    override-pull: |
      craftctl default
      TAG=$(git describe --tags)
      SNAP_GIT_VERSION=$(git -C $CRAFT_PROJECT_DIR describe --always --dirty --abbrev=10)
      craftctl set version="${TAG#v}+snap-${SNAP_GIT_VERSION}"
  scripts:
    plugin: dump
    source: snap/local
    organize:
      smartctl_exporter.wrapper: bin/smartctl_exporter.wrapper
